# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: engine.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='engine.proto',
  package='test',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x65ngine.proto\x12\x04test\"\x13\n\x11RequestCreateGame\"(\n\x12ResponseCreateGame\x12\x12\n\ncreate_res\x18\x01 \x01(\t\"$\n\x0fRequestJoinGame\x12\x11\n\tjoin_info\x18\x01 \x03(\t\"|\n\x10ResponseJoinGame\x12\x37\n\tjoin_info\x18\x01 \x03(\x0b\x32$.test.ResponseJoinGame.JoinInfoEntry\x1a/\n\rJoinInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x8a\x01\n\x06\x45ngine\x12\x42\n\x0b\x63reate_game\x12\x17.test.RequestCreateGame\x1a\x18.test.ResponseCreateGame\"\x00\x12<\n\tjoin_game\x12\x15.test.RequestJoinGame\x1a\x16.test.ResponseJoinGame\"\x00'
)




_REQUESTCREATEGAME = _descriptor.Descriptor(
  name='RequestCreateGame',
  full_name='test.RequestCreateGame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=41,
)


_RESPONSECREATEGAME = _descriptor.Descriptor(
  name='ResponseCreateGame',
  full_name='test.ResponseCreateGame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='create_res', full_name='test.ResponseCreateGame.create_res', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=83,
)


_REQUESTJOINGAME = _descriptor.Descriptor(
  name='RequestJoinGame',
  full_name='test.RequestJoinGame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='join_info', full_name='test.RequestJoinGame.join_info', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=121,
)


_RESPONSEJOINGAME_JOININFOENTRY = _descriptor.Descriptor(
  name='JoinInfoEntry',
  full_name='test.ResponseJoinGame.JoinInfoEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='test.ResponseJoinGame.JoinInfoEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='test.ResponseJoinGame.JoinInfoEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=247,
)

_RESPONSEJOINGAME = _descriptor.Descriptor(
  name='ResponseJoinGame',
  full_name='test.ResponseJoinGame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='join_info', full_name='test.ResponseJoinGame.join_info', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_RESPONSEJOINGAME_JOININFOENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=247,
)

_RESPONSEJOINGAME_JOININFOENTRY.containing_type = _RESPONSEJOINGAME
_RESPONSEJOINGAME.fields_by_name['join_info'].message_type = _RESPONSEJOINGAME_JOININFOENTRY
DESCRIPTOR.message_types_by_name['RequestCreateGame'] = _REQUESTCREATEGAME
DESCRIPTOR.message_types_by_name['ResponseCreateGame'] = _RESPONSECREATEGAME
DESCRIPTOR.message_types_by_name['RequestJoinGame'] = _REQUESTJOINGAME
DESCRIPTOR.message_types_by_name['ResponseJoinGame'] = _RESPONSEJOINGAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestCreateGame = _reflection.GeneratedProtocolMessageType('RequestCreateGame', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTCREATEGAME,
  '__module__' : 'engine_pb2'
  # @@protoc_insertion_point(class_scope:test.RequestCreateGame)
  })
_sym_db.RegisterMessage(RequestCreateGame)

ResponseCreateGame = _reflection.GeneratedProtocolMessageType('ResponseCreateGame', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSECREATEGAME,
  '__module__' : 'engine_pb2'
  # @@protoc_insertion_point(class_scope:test.ResponseCreateGame)
  })
_sym_db.RegisterMessage(ResponseCreateGame)

RequestJoinGame = _reflection.GeneratedProtocolMessageType('RequestJoinGame', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTJOINGAME,
  '__module__' : 'engine_pb2'
  # @@protoc_insertion_point(class_scope:test.RequestJoinGame)
  })
_sym_db.RegisterMessage(RequestJoinGame)

ResponseJoinGame = _reflection.GeneratedProtocolMessageType('ResponseJoinGame', (_message.Message,), {

  'JoinInfoEntry' : _reflection.GeneratedProtocolMessageType('JoinInfoEntry', (_message.Message,), {
    'DESCRIPTOR' : _RESPONSEJOINGAME_JOININFOENTRY,
    '__module__' : 'engine_pb2'
    # @@protoc_insertion_point(class_scope:test.ResponseJoinGame.JoinInfoEntry)
    })
  ,
  'DESCRIPTOR' : _RESPONSEJOINGAME,
  '__module__' : 'engine_pb2'
  # @@protoc_insertion_point(class_scope:test.ResponseJoinGame)
  })
_sym_db.RegisterMessage(ResponseJoinGame)
_sym_db.RegisterMessage(ResponseJoinGame.JoinInfoEntry)


_RESPONSEJOINGAME_JOININFOENTRY._options = None

_ENGINE = _descriptor.ServiceDescriptor(
  name='Engine',
  full_name='test.Engine',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=250,
  serialized_end=388,
  methods=[
  _descriptor.MethodDescriptor(
    name='create_game',
    full_name='test.Engine.create_game',
    index=0,
    containing_service=None,
    input_type=_REQUESTCREATEGAME,
    output_type=_RESPONSECREATEGAME,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='join_game',
    full_name='test.Engine.join_game',
    index=1,
    containing_service=None,
    input_type=_REQUESTJOINGAME,
    output_type=_RESPONSEJOINGAME,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ENGINE)

DESCRIPTOR.services_by_name['Engine'] = _ENGINE

# @@protoc_insertion_point(module_scope)
