# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import engine_pb2 as engine__pb2


class EngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create_game = channel.unary_unary(
                '/test.Engine/create_game',
                request_serializer=engine__pb2.RequestCreateGame.SerializeToString,
                response_deserializer=engine__pb2.ResponseCreateGame.FromString,
                )
        self.join_game = channel.unary_unary(
                '/test.Engine/join_game',
                request_serializer=engine__pb2.RequestJoinGame.SerializeToString,
                response_deserializer=engine__pb2.ResponseJoinGame.FromString,
                )


class EngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def create_game(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def join_game(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create_game': grpc.unary_unary_rpc_method_handler(
                    servicer.create_game,
                    request_deserializer=engine__pb2.RequestCreateGame.FromString,
                    response_serializer=engine__pb2.ResponseCreateGame.SerializeToString,
            ),
            'join_game': grpc.unary_unary_rpc_method_handler(
                    servicer.join_game,
                    request_deserializer=engine__pb2.RequestJoinGame.FromString,
                    response_serializer=engine__pb2.ResponseJoinGame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'test.Engine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Engine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def create_game(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/test.Engine/create_game',
            engine__pb2.RequestCreateGame.SerializeToString,
            engine__pb2.ResponseCreateGame.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def join_game(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/test.Engine/join_game',
            engine__pb2.RequestJoinGame.SerializeToString,
            engine__pb2.ResponseJoinGame.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
